global using QuizAppPG.DTOs;
global using QuizAppPG.Services.Api;
global using QuizAppPG.Services.Local;
global using QuizAppPG.Services.Realtime;
global using QuizAppPG.Utilities;
global using QuizAppPG.ViewModels;
global using CommunityToolkit.Mvvm.ComponentModel;
global using CommunityToolkit.Mvvm.Input;
global using CommunityToolkit.Maui;
