using CommunityToolkit.Mvvm.ComponentModel;
using CommunityToolkit.Mvvm.Input;
using QuizAppPG.DTOs; // Corrected: Use QuizAppPG.DTOs for DTOs
using QuizAppPG.Services.Realtime;
using QuizAppPG.Services.Local; // For IDialogService, INavigationService, ISecureStorageService
using QuizAppPG.Views.Leaderboard; // Assuming navigating to leaderboard after game
using System.Collections.ObjectModel;
using System.Linq; // For FirstOrDefault
using System; // For Guid
using Microsoft.Maui.Controls; // For MainThread
using Microsoft.AspNetCore.SignalR.Client; // Added for HubConnectionState

namespace QuizAppPG.ViewModels.Game
{
    [QueryProperty(nameof(GameSessionId), "GameSessionId")]
    public partial class MultiplayerGameViewModel : BaseViewModel // Added `partial`
    {
        private readonly IGameHubClient _gameHubClient;
        // _dialogService, _navigationService, _secureStorageService are inherited

        [ObservableProperty]
        private string gameSessionId = string.Empty; // Initialized to prevent CS8618

        [ObservableProperty]
        private QuestionDto? currentQuestion; // Made nullable

        [ObservableProperty]
        private int currentQuestionNumber;

        [ObservableProperty]
        private int totalQuestions; // You might get this from GameSessionDetails or hardcode 10

        [ObservableProperty]
        private string selectedAnswer = string.Empty; // Initialized to prevent CS8618

        [ObservableProperty]
        private bool isAnswerSubmitted;

        [ObservableProperty]
        private string feedbackMessage = string.Empty; // Initialized to prevent CS8618

        [ObservableProperty]
        private string currentPlayerUsername = string.Empty; // Initialized to prevent CS8618

        [ObservableProperty]
        private ObservableCollection<GameSessionPlayerDto> players = new(); // Initialized to prevent CS8618


        public MultiplayerGameViewModel(
            IGameHubClient gameHubClient,
            IDialogService dialogService,
            INavigationService navigationService,
            ISecureStorageService secureStorageService) // <<< ADD THIS PARAMETER
            : base(navigationService, dialogService, secureStorageService) // <<< PASS THIS PARAMETER
        {
            _gameHubClient = gameHubClient;
            Title = "Spelar Quiz"; // Title is a property of BaseViewModel

            // Subscribe to SignalR events
            _gameHubClient.ReceiveQuestion += OnReceiveQuestion;
            _gameHubClient.AnswerResult += OnAnswerResult;
            _gameHubClient.PlayerScoreUpdated += OnPlayerScoreUpdated;
            _gameHubClient.GameOver += OnGameOver;
            _gameHubClient.ReceiveError += OnReceiveError;

            _ = InitializePlayerUsername(); // Use `_ =` to suppress warning for unawaited Task
        }

        private async Task InitializePlayerUsername()
        {
            CurrentPlayerUsername = await _secureStorageService.GetUsernameAsync() ?? "Okänd spelare"; // Handle potential null
        }

        // --- QueryProperty handler ---
        // This method needs to be partial as it's auto-generated by the `QueryProperty` attribute
        partial void OnGameSessionIdChanged(string value)
        {
            if (!string.IsNullOrEmpty(value))
            {
                _ = RequestNextQuestionAsync(); // Use `_ =` to suppress warning for unawaited Task
                TotalQuestions = 10; // Placeholder, this needs to be fetched from a service if dynamic
            }
        }

        // --- Public methods for page lifecycle ---
        public override void OnAppearing() // Override BaseViewModel's method
        {
            base.OnAppearing(); // Call base implementation
            // Ensure hub is connected and joined, though GameLobby should handle this.
            // Just in case, you might add a check here to ensure player is in group.
        }

        public override void OnDisappearing() // Override BaseViewModel's method
        {
            base.OnDisappearing(); // Call base implementation
            // Unsubscribe from SignalR events to prevent memory leaks
            _gameHubClient.ReceiveQuestion -= OnReceiveQuestion;
            _gameHubClient.AnswerResult -= OnAnswerResult;
            _gameHubClient.PlayerScoreUpdated -= OnPlayerScoreUpdated;
            _gameHubClient.GameOver -= OnGameOver;
            _gameHubClient.ReceiveError -= OnReceiveError;
        }

        // --- SignalR Event Handlers ---
        private void OnReceiveQuestion(QuestionDto question, int questionNumber, bool isLastQuestion)
        {
            MainThread.BeginInvokeOnMainThread(() =>
            {
                CurrentQuestion = question;
                CurrentQuestionNumber = questionNumber;
                SelectedAnswer = string.Empty;
                IsAnswerSubmitted = false;
                FeedbackMessage = string.Empty;
                // isLastQuestion can be used to control UI for final question
            });
        }

        private void OnAnswerResult(AnswerResultDto result)
        {
            MainThread.BeginInvokeOnMainThread(async () => // Changed to async void for event handler
            {
                IsAnswerSubmitted = true;
                if (result.IsCorrect)
                {
                    FeedbackMessage = $"Rätt svar! Du fick {result.PointsAwarded} poäng. Din totala poäng: {result.CurrentScore}";
                }
                else
                {
                    FeedbackMessage = $"Fel svar. Du fick 0 poäng. Rätt svar var: {CurrentQuestion?.CorrectAnswer}. Din totala poäng: {result.CurrentScore}";
                }
            });
        }

        private void OnPlayerScoreUpdated(string username, int score)
        {
            MainThread.BeginInvokeOnMainThread(() =>
            {
                var player = Players.FirstOrDefault(p => p.Username == username);
                if (player != null)
                {
                    player.Score = score; // Update score for display
                    // You might want to re-order the Players collection here to update leaderboard display
                    // Players = new ObservableCollection<GameSessionPlayerDto>(Players.OrderByDescending(p => p.Score));
                }
            });
        }

        private void OnGameOver()
        {
            MainThread.BeginInvokeOnMainThread(async () =>
            {
                await _dialogService.ShowAlertAsync("Spel Slut", "Spelet är slut! Se resultaten.");
                await _navigationService.GoToAsync($"//{nameof(LeaderboardPage)}");
                await _gameHubClient.DisconnectAsync();
            });
        }

        private void OnReceiveError(string error)
        {
            MainThread.BeginInvokeOnMainThread(async () =>
            {
                await _dialogService.ShowAlertAsync("Fel från server", error);
            });
        }

        // --- Commands ---
        [RelayCommand(CanExecute = nameof(CanSubmitAnswer))]
        private async Task SubmitAnswerAsync()
        {
            if (IsBusy || IsAnswerSubmitted) return;

            IsBusy = true;
            try
            {
                if (CurrentQuestion == null || string.IsNullOrWhiteSpace(SelectedAnswer))
                {
                    await _dialogService.ShowAlertAsync("Varning", "Vänligen välj ett svar.");
                    return;
                }

                var submitDto = new SubmitAnswerDto
                {
                    QuestionId = CurrentQuestion.Id,
                    SubmittedAnswer = SelectedAnswer,
                    GameSessionId = Guid.Parse(GameSessionId)
                };

                await _gameHubClient.SubmitAnswer(GameSessionId, submitDto);
            }
            catch (Exception ex)
            {
                await _dialogService.ShowAlertAsync("Fel", $"Kude inte skicka svar: {ex.Message}");
            }
            finally
            {
                IsBusy = false;
            }
        }

        private bool CanSubmitAnswer()
        {
            return !IsBusy && !IsAnswerSubmitted && CurrentQuestion != null;
        }


        [RelayCommand(CanExecute = nameof(CanRequestNextQuestion))]
        private async Task RequestNextQuestionAsync()
        {
            if (IsBusy) return;

            IsBusy = true;
            try
            {
                await _gameHubClient.RequestNextQuestion(GameSessionId);
            }
            catch (Exception ex)
            {
                await _dialogService.ShowAlertAsync("Fel", $"Kude inte hämta nästa fråga: {ex.Message}");
            }
            finally
            {
                IsBusy = false;
            }
        }

        private bool CanRequestNextQuestion()
        {
            return !IsBusy;
        }
    }
}